services:
  api:
    paths:
      - services/api
    depends-on:
      - sharedd
  worker:
    paths:
      - services/worker
    depends-on:
      - sharedd
  notifier:
    paths:
      - services/notifier
  shared:
    paths:
      - libs/shared
  esto: [no cierra
